<nav class="navbar navbar-expand-sm navbar-dark" style="background-color: red;">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
        aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation"></button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

        <?php foreach( $mencat->items as $elemento): ?>
            <li class="nav-item active">
                <a class="nav-link" href="#">
                  <?php echo $elemento->nombre ?>
                </a>
            </li>
        <?php endforeach ?>


        </ul>
    </div>
</nav>



